# Generated by Django 4.0.4 on 2022-05-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0007_logs_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='pass.customer', verbose_name='Ник посетителя'),
        ),
    ]
